### ISSUE TITLE
iMessage and FaceTime does not work

### ISSUE THREAD

**Issue by Oloye-Dev** [jkbuha/XPS-9500-IceLake-OpenCore#1]
Just like the title says. Both apps don't work and I created my Mac serial number using gensmbios and also verified the serial I picked wasn't already picked. I used your efi and changed nothing. 
Also the picture below shows just MacBook pro instead of MacBook pro 16 inches and other details beneath.

![PXL₆_20231013_125651](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/96616860/59574e5a-2948-4a27-adb0-86f8d026d9ca)

Also, when I go to device info, it says "This device cannot be used to receive Apple ID verification codes."

**Comment by jkbuha** [comment]
Facetime/iMessage work well with this EFI config, provided you follow the rules. Suggest you take another look at this guide: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html
