### ISSUE TITLE
Power management

### ISSUE THREAD

**Issue by emilevirus** [jkbuha/XPS-9500-IceLake-OpenCore#11]
I see in your screenshot that CPU pkg power should idle at around 2.5W. I have the i7 10875H and it never goes below 5.5W. Did you do something post installation to get those numbers?

**Comment by jkbuha** [comment]
I additionally undervolt my i9-10885H processor, but presumably it's within
the same tolerance as your 10785H. There's some additional optimisation on
aspm which you can inject via device-properties, but I doubt it would be
50% power. It sounds like your OS is incurring additional overheads; check
your activity monitor to see what's additionally consuming your resources.

**Comment by jkbuha** [comment]
Closing this issue.
