### ISSUE TITLE
Trackpad only works after waking from sleep

### ISSUE THREAD

**Issue by webstar1** [jkbuha/XPS-9500-IceLake-OpenCore#13]
I am using your trackpad solution on my XPS 9300 and for some reason it only works only once I put the laptop to sleep. On a cold boot, the trackpad doesn't work, only very few times has it worked, such as when I switched to Opencore Debug, it worked since boot. however shutting down and loading again, same issue is apparent.

I face the same issue of trackpad in polling mode without your SSDT-TPXX.aml. Is there any other SSDTs or patches for this fix which I am missing? I have attached my log for reference although I cant see anything going wrong.

[opencore-2024-04-10-021053.txt](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/files/14926570/opencore-2024-04-10-021053.txt)

**Comment by jkbuha** [comment]
You shouldn't be using this repo for the 9300 trackpad, as it has ACPI
dependencies that require external files. Use this instead, it works well:

https://github.com/Baio1977/EFI-Hackintosh-collection/blob/main/EFI%20Laptop%20/DELL/XPS%209300%20Ice%20Lake/0.8.3/EFI/OC/ACPI/SSDT-XPS_9300.aml

**Comment by webstar1** [comment]
Thank you so much, I cant believe there was already a solution out there. Trackpad works fine now
