### ISSUE TITLE
CPU Turbo Issue

### ISSUE THREAD

**Issue by gzliudianxin** [jkbuha/XPS-9500-IceLake-OpenCore#15]
Hello jkbuha, I have discovered an issue regarding the maximum frequency of the CPU。
I found through testing that although the maximum frequency requirement is 4.5G, 
but the CPU core frequency can only reach 3.5G。
<img width="1280" alt="截屏2024-04-30 10 01 58" src="https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/161866307/836509a7-d3b1-40bf-8e2c-a4b83a303e2e">
<img width="577" alt="截屏2024-04-30 10 02 50" src="https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/161866307/ab3bb8f2-5637-476b-92bc-27936f9908c8">

Have you ever encountered this problem？

Looking forward to your help with great sincerity！

**Comment by jkbuha** [comment]
Hey - That's most likely because you're not using a custom CPUFriendDataProvider for your i5-10300H. Try generating one and replacing it with the existing and see if the frequency picks up.

**Comment by gzliudianxin** [comment]
I have discovered the reason, it is because of my system version Sonoma 14.2.1.
There is an issue with this version. When the icloud function is enabled, the transparencyd and identyiservicesd processes will automatically start and occupy a high CPU usage after booting up.
If two processes are forcibly shut down, the CPU usage frequency will drop to a normal level of around 1.2G under low load conditions, and it can also reach a frequency of 4.5G during testing.
This issue can be resolved by upgrading to version 14.4. If anyone else has encountered this issue, please refer to it.
![WechatIMG23](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/161866307/4a593402-0961-43dd-8262-d126ee0530eb)
