### ISSUE TITLE
Problems with the cooling system and cpu frequency

### ISSUE THREAD

**Issue by yago85** [jkbuha/XPS-9500-IceLake-OpenCore#16]
Thank you so much for EFI! Please clarify how your cooling system works? On my Dell Precision 5550 with i9-10885H with a low load, the fans work intermittently, turn on and off very often, and at a temperature of 45 - 50 degrees Celcius they reach 3375 RPM. Does it work the same for you or more smoothly? I also noticed that the maximum CPU frequency does not rise above 3.8G, and I tried different options both with and without undervolting. At the moment I am working with the parameters as in the screenshot.
![screen 2024-05-02 в 21 40 14](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/52779393/4ebcf63c-cf3e-4faa-984d-eddd9237dbb5)

**Comment by jkbuha** [comment]
My CPU is the i9-10885 as well, but fans rarely kick in unless the machine
is under some serious load. However I have not seen the frequencies above
3.8GHz either; so it's likely an issue with (not having) an optimised
CPUFriendDataProvider.

Happy to have a play with it when I get some spare time in the coming
days/weeks unless you want to submit one yourself for testing?
ᐧ

**Comment by yago85** [comment]
I'm also testing different options at the moment. Also, I still haven’t been able to figure out the fans, so I’m solving this problem with Macs Fan Control. But when using this application to adjust the fan speed, for some reason they stop responding to changes in the display brightness key and the battery charge indication freezes in one position. Unfortunately, this is my first experience with open core, so I’m moving very slowly so far))

**Comment by jkbuha** [comment]
With latest CPUFriendDataProvider I have managed to bring down the temps considerably, fans do not switch on now in macos.

Also, for those who wish to push their system further, there's a few modded heatpipe chambers out there on the market for the 95x0. Anyone who has tried one can report back with their results :)

**Comment by MirComputers** [comment]
> Thank you so much for EFI! Please clarify how your cooling system works? On my Dell Precision 5550 with i9-10885H with a low load, the fans work intermittently, turn on and off very often, and at a temperature of 45 - 50 degrees Celcius they reach 3375 RPM. Does it work the same for you or more smoothly? I also noticed that the maximum CPU frequency does not rise above 3.8G, and I tried different options both with and without undervolting. At the moment I am working with the parameters as in the screenshot. ![screen 2024-05-02 в 21 40 14](https://github.com/jkbuha/XPS-9500-IceLake-OpenCore/assets/52779393/4ebcf63c-cf3e-4faa-984d-eddd9237dbb5)

It is totally useless to undervolt Core and Cache different amounts on anything after Skylake, it will apply the lowest value to both. Also iGpu is tied to unslice wich you set to 0, try something like -75 -65 -75 -50 -65 -0

I have my 10750h at -115 -90 -115 -75 -90 0 , but i installed many thermal pads between the back of the motherboard in the CPU and VRM area and the top case, my machine becomes super hot on top but stays cooler inside, and set a 50w power limit; this keeps the cpu package under 90c even in the current italian summer 2026 heatwave!
