### ISSUE TITLE
10875h freq limited

### ISSUE THREAD

**Issue by BitBricker** [jkbuha/XPS-9500-IceLake-OpenCore#17]
Firstly, thank you for a great EFI, as it has helped tremendously. In 14.4, it did not work right away out of the box, and had bunch of reboots. All were solved with updated wifi driver (removed the 2 provided and used single kext) and setting secure boot mode to disabled. 
bow to a problem I can’t seem to figure out. Have this setup as 14.4 on my xps 9500 with 4k and i7-10875h. The system works great m, however did notice that geekbench single core performance is much lower in hackintosh vs windows. In windows, I’m at typical 1700/7000 score however on hack it’s 1200/6600. The multi core is not bad, however single core is way behind. I did some digging and see that single core loads, the cpu only reaches 3.6ghz (vs 4.8ghz) in windows. No idea on what can be limiting the request, but I know it’s not heat as it barely reaches 70c (90s in windows). Wondering if you ran your system on geekbench and monitored core speed utilization. In Intel power gadget, Core Req is 5.1, which is perfectly setup for the 10875h however core max is only 3.6ghz. Again heat is by far not an issue, power limiter 1 and 2 are not triggered, wattage is way below PL1, and battery is charged and plugged in. Just can’t figure it out. 
Thanks!

**Comment by jkbuha** [comment]
I'm seeing similar results to yours on geekbench, which means the
CPUFriendDatProvider needs to be optimised. I haven't yet
investigated this area properly, but happy to test/refine any optimised
kexts you've done.
ᐧ

**Comment by BitBricker** [comment]
Thanks for reply! You know, I have never messed with/created CPUFriendDataProvider next before but will research it today. I do have a system here to test it on so if I’m successful, I’ll let you know.

**Comment by jkbuha** [comment]
With my latest CPUFriendData commit (and switching to MBA9,1) the scores are same as windows - https://browser.geekbench.com/v6/cpu/7273425.

Closing this thread.
