### ISSUE TITLE
Backlit screen slow response

### ISSUE THREAD

**Issue by hieudn3012** [jkbuha/XPS-9500-IceLake-OpenCore#18]
Hi. Thank you for your files. It works great on my XPS 9500. However, it still has one problem: everytime I open the computer, it takes 2-3 minutes for the screen backlit to light up (the content still works fine, I can even control the computer with a flashlight point to the screen) can you help address the issue? Thank you.

**Comment by jkbuha** [comment]
Never seen this before. Could you try the following:

1. Try the macos shortcut to switch off and on the screen (Ctrl+Shift+Insert)
2. Apply the RTC wake disable patch in the recent commit, reboot and see if it happens again?

**Comment by hieudn3012** [comment]
Tried with the second option. Problem seems to be solved. Thank you!
