### ISSUE TITLE
AirDrop, Hand-off and other Continuity features don't work 

### ISSUE THREAD

**Issue by SanoLitch** [jkbuha/XPS-9500-IceLake-OpenCore#5]
Seems like there are some issues with bluetooth configuration. Tried to turn on ExtendBTFeatureFlags but no success. Have anyone similar problems?

OS: Sonoma 14.1.2

**Comment by jkbuha** [comment]
Haven't tested it on Sonoma yet as there are too many moving parts atm. But all airportltwm.kext features work fine as indicated on monterey and ventura. Check that your bluetooth is powered on (from System Information -> Bluetooth)

**Comment by SanoLitch** [comment]
@jkbuha bluetooth works well, issue related only for features above. As I understand without ExtendBTFeatureFlags these features won't be work at all. When I turned it on nothing change actually, but I got issue with AirPods Pro 2 - it connected but no sound was, with turned off works well.

**Comment by jkbuha** [comment]
interesting, not sure what the issue is on sonoma. but on ventura it works as expected (my airpods pro and wireless keyboard/mouse work perfectly and airdrop/handoff work well too). maybe it's a sonoma-specific issue with the driver (in which case open a bug with the airportltwm devs?)

**Comment by SanoLitch** [comment]
@jkbuha I've got some positive result...I've installed Venture again, made all configuration for SMBIOS and AppleID and it almost worked. I had the same issue with Airpods and noticed that handoff worked a  bit weird but worked. Then I upgraded to Sonoma and Airpods works well now, but handoff is still weird as it on Venture was. 
Looks like it works in only one way - Sonoma can received hand0ff data from other devices but can't to send it them. The same situation with AirDrop. So now I have:
- Hackintosh (this Sonoma) can see data from my real macMini (Sonoma also) and IPhone (Sonoma also as I remember)
- macMini can see IPhone but can't Hackintosh
- IPhone can see macMini but can't Hackintosh
Actually I can try with IPad else, but I think result will be same. 

Now I almost satisfied with the result, but just for interest - did you try to send some text FROM hackintosh TO other Apple devices via universal clipboard? Sorry, but I'm so close to win, I need a little bit more information XD

**Comment by jkbuha** [comment]
Airportltwm handoff only works one way. From their FAQ:

Note: Handoff only works in one direction in macOS Monterey and newer (from mobile devices to Mac) due to the broken bluetoothd newly ported from iOS.

[#](https://openintelwireless.github.io/itlwm/FAQ#can-i-use-it-to-create-a-personal-hotspot)

**Comment by SanoLitch** [comment]
@jkbuha oh...will wait for fix, thx
