### ISSUE TITLE
Resuming from hibernation takes almost a minute

### ISSUE THREAD

**Issue by jlempen** [jkbuha/XPS-9500-IceLake-OpenCore#9]
Hey @jkbuha,
Thanks for maintaining this excellent repo for the XPS 9500 / Precision 5550!

My specs are a Precision 5550 i7-10850H with 32GB of RAM and the nvidia Quadro T1000 dGPU powering a 3840x2400 UHD display. The SSD is a 2TB WD Black SN850X. The OS is Ventura v13.6.5.

On my system, resuming from hibernation takes 55 seconds. Is this specific to my machine and/or amount of RAM or is this normal? 55 seconds is actually more than the time it takes for a cold boot. As a point of comparison, my anemic Microsoft Surface Go 2 with 8GB of RAM running macOS Ventura using [this EFI](https://github.com/jlempen/Surface-Go-2-OpenCore) resumes from hibernation in 15 seconds. Of course, the SGO2 has only 8GB of RAM compared to my Precision 5550's 32GB.

How long does your machine take to resume from hibernation?

**Comment by jkbuha** [comment]
There are a few caveats to this answer, but the quick explanation is that
resume from hibernation is mostly dependent on amount of ram installed, and
ram speed.

There's some further optimisation that will be done at a later stage (there
are S4 boot modes that are faster than traditional hibernate/resume
cycles), but it's likely to take time and possibly introduce some
instability.
ᐧ

**Comment by jkbuha** [comment]
Closing this for now, unless there are any more issues with time to wake.
